# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ad144be470d31af8d061772d3e406419b5e7286c6221df6121dfb246fb5b60bbdf8efe6b336bf684ae69cfc6c0cb57d198f6abb379ed8076b38a02a187f8440

test:
  secret_key_base: 5ea266c51db23e39104376da49f5507da932b92deb4c0139c311a13c25fecb3d82ba0202601518532b86b4c800fd192215185d838bd6c81ecc3a15954fe9b12b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
